<?php
$drinks = [
    [
    "id" =>1,
    "type" =>"warm",
    "name" =>"expresso sans sucre",
    "sugar"=> false,
    "milk" => false,
    "price"=> 2,
    "image" => "https://res.cloudinary.com/yuppiechef/image/upload/c_fill,e_sharpen:40,h_233,q_auto,w_233/v1/contentdocs/28453/picture20170127095806",
    ],

    [
        "id" =>2,
        "type" =>"warm",
        "name" =>"expresso",
        "sugar"=> true,
        "milk" => false,
        "price"=> 2,
        "image" => "https://res.cloudinary.com/yuppiechef/image/upload/c_fill,e_sharpen:40,h_233,q_auto,w_233/v1/contentdocs/28453/picture20170127095806",
    ],
    [
        "id" =>3,
        "type" =>"warm",
        "name" =>"latte sans sucre",
        "sugar"=> false,
        "milk" => true,
        "price"=> 3,
        "image" => "https://th.bing.com/th/id/OIP.OvGFfMI08Gw42YjfpM8LtQHaE8?w=283&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    [
        "id" =>4,
        "type" =>"warm",
        "name" =>"latte ",
        "sugar"=> true,
        "milk" => true,
        "price"=> 3,
        "image" => "https://th.bing.com/th/id/OIP.OvGFfMI08Gw42YjfpM8LtQHaE8?w=283&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    [
        "id" =>5,
        "type" =>"warm",
        "name" =>"mochaccino sans sucre ",
        "sugar"=> false,
        "milk" => true,
        "price"=> 3,
        "image" => "https://th.bing.com/th/id/OIP.fTLFk5mx2bdDaXkRoIhcFgHaHc?w=181&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    [
        "id" =>6,
        "type" =>"warm",
        "name" =>"mochaccino",
        "sugar"=> true,
        "milk" => true,
        "price"=> 3,
        "image" => "https://th.bing.com/th/id/OIP.fTLFk5mx2bdDaXkRoIhcFgHaHc?w=181&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    [
    "id" =>7,
    "type" =>"warm",
    "name" =>"cappucino",
    "sugar"=> true,
    "milk" => true,
    "price"=> 4,
    "image" =>"https://th.bing.com/th/id/OIP.cyCmZYVSNiUbvseIz7hKggHaFj?w=235&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    [
        "id" =>8,
        "type" =>"warm",
        "name" =>"capucino sans sucre",
        "sugar"=> false,
        "milk" => true,
        "price"=> 3,
        "image" =>"https://th.bing.com/th/id/OIP.cyCmZYVSNiUbvseIz7hKggHaFj?w=235&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],

    [
        "id" =>9,
        "name" =>"coca",
        "type" =>"cold",
        "sugar"=> false,
        "milk" => false,
        "price"=> 1.50,
        "image" => "https://th.bing.com/th/id/OIP.gOSWD16OMZ6vAMmKT8ltUwHaHa?pid=ImgDet&rs=1",
    ],
    [
        "id" =>10,
        "type" =>"cold",
        "name" =>"orangina",
        "sugar"=> false,
        "milk" => false,
        "price"=> 1.50,
        "image"=> "https://th.bing.com/th/id/OIP.grf137oCmpEJZkt-cHBGpgHaHa?w=208&h=207&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    [
        "id" =>11,
        "type" =>"cold",
        "name" =>"oasis",
        "sugar"=> false,
        "milk" => false,
        "price"=> 1.50,
        "image"=> "https://th.bing.com/th/id/OIP.r7AabtRikOqOR7Uvw3j0aQHaHa?w=210&h=211&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    ],
    ]
    ?>